---
- hosts: 172.31.12.175 
  become: yes
  tasks: 
  - name: install tree
    apt: 
      name: tree
      state: present

  - name: install wget
    apt: 
      name: wget
      statee: present
    ignore_errors: true

  - name: install git
    apt:
       name: git
       state: present