---
-  hosts: all
   become: yes
   tasks:
   - name: copy file from the internet
     get_url:
        url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
        dest: /home/ubuntu/jenkins.war
