---
-  hosts: all
   become: yes
   tasks:
     - name: install apache2 on nodes
       apt: 
         name: apache2
         state: present

     - name: start apache 2
       service: 
           name: apache2
           state: started
           enabled: yes