---
-  hosts: all
   become: yes
   tasks:
     - name: uninstall apache2 on nodes
       apt: 
         name: apache2
         state: absent

     - name: stop apache 2
       service: 
           name: apache2
           state: stop
           